package sbc

// KeyBuilder is an interface that defines a method to build a key based on a value of type T.
// The BuildKey method takes a value of type T as a parameter and returns a string key.
type KeyBuilder[T comparable] interface {
	BuildKey(t T) string
}

// KeyBuilderFunc is a type that represents a function that builds a key based on a value of type T.
// The function takes a value of type T as a parameter and returns a string key.
type KeyBuilderFunc[T comparable] func(t T) string

// BuildKey returns the string key generated by the KeyBuilderFunc for the given input value.
func (k KeyBuilderFunc[T]) BuildKey(t T) string {
	return k(t)
}
