package sbckey

import (
	"fmt"
	sbc "github.com/Autodoc-Technology/streaming-based-config"
	"strings"
)

// ConsulDefaultKeyBuilder is a function that returns a key builder for Consul.
// It builds a key based on a value of a comparable type T.
// The built key is generated by formatting the value's type as a string and removing the leading slash if present.
//
// Example usage:
//
//	builder := ConsulDefaultKeyBuilder[int]()
//	key := builder.BuildKey(42) // key = "int"
func ConsulDefaultKeyBuilder[T comparable]() sbc.KeyBuilder[T] {
	return sbc.KeyBuilderFunc[T](func(t T) string {
		val := fmt.Sprintf("%T", t)
		return strings.TrimPrefix(val, "/")
	})
}
