package sbckey

import (
	"fmt"
	"strings"

	sbc "github.com/Autodoc-Technology/streaming-based-config"
)

// NoPrefix defines an empty string constant, typically used to indicate the absence of any prefix.
const NoPrefix = ""

// ConsulDefaultKeyBuilder is a function that returns a key builder for Consul.
// It builds a key based on a value of an any type T.
// The built key is generated by formatting the value's type as a string and removing the leading slash if present.
//
// Example usage:
//
//	builder := ConsulDefaultKeyBuilder[int]()
//	key := builder.BuildKey(42) // key = "int"
//
//	builder := ConsulDefaultKeyBuilder[int]("prefix/")
//	key := builder.BuildKey(42) // key = "prefix/int"
func ConsulDefaultKeyBuilder[T any](prefix string) sbc.KeyBuilder[T] {
	return sbc.KeyBuilderFunc[T](func(t T) string {
		val := fmt.Sprintf("%T", t)
		return prefix + strings.TrimPrefix(val, "/")
	})
}
